spring:
  application:
    name: first-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: todo_route
              uri: lb://first-backend  # The base URI of the backend service
              predicates:
                - Path=/**
              filters:
                - AddResponseHeader=X-Gateway-Request, True
                - name: CircuitBreaker
                  args:
                    name: my_todo_circuitbreaker
                    fallbackUri: forward:/fallback-todo
            - id: test_cb_route
              uri: https://httpbin.org/  # The base URI of the backend service
              predicates:
                - Path=/test_cb/**
              filters:
                - RewritePath=/test_cb/?(?<delay>.*), /delay/$\{delay}
                - AddResponseHeader=X-Gateway-Request, True
                - name: CircuitBreaker
                  args:
                    name: my_test_cb_circuitbreaker
                    fallbackUri: forward:/fallback-todo

eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_SERVER_URL}
        
server:
  port: 8080